home/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.home, name ='home')
]

jobMap/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'job'

urlpatterns = [
    path('job_map_search/', views.job_map_search, name ='job_map_search'),
    path('job_map_search_cluster/', views.job_map_search_cluster, name ='job_map_search_cluster'),
    path('job_map_search_heat/', views.job_map_search_heat, name ='job_map_search_heat'),
    path("job_map_search_list/", views.job_map_search_list, name ='job_map_search_list'),
    path("job_map_all/", views.job_map_all, name ='job_map_all'),
]

smart_recruiting_map/urls.py
from django.contrib import admin
from django.urls import path
from vivaMountainMap import views

urlpatterns = [
    path('admin/', admin.site.urls),
]

vivaMountainMap/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'mountain'

urlpatterns = [
    path('mountain_map/info/<int:no>', views.view_info, name ='info'),
    path('mountain_map/', views.mountain_map, name ='mountain_map')
]

jobMap/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'home/home.html')

jobMap/views.py
from django.shortcuts import render
from jobMap.jobAPI import jobAPI
from pymongo import MongoClient
from django.core.paginator import Paginator

# Create your views here.
def get_form(requests):
    data = dict()
    if len(requests.GET) >=3:
        data['keyword'] = requests.GET['key']
        data['max_page'] = requests.GET['max_page']
        data['careerType'] = requests.GET['careerType']
        data['flag'] = True
    else:
        # with MongoClient('mongodb://127.0.0.1:27017') as client:
            # data = list(client.Jobdata.keyword.find())[0]
        with MongoClient('mongodb://192.168.0.134:8088') as client:
            data = list(client.Jobinfo.keyword.find())[0]
            data['flag'] = False
    return data

def job_map_search(requests):
    data = get_form(requests)
    job = jobAPI()
    m = job.get_searchmap(data)
    datas = {'mountain_map':m, 'data':data}
    return render(requests, 'jobMap/job_map_search.html', context=datas)

def job_map_search_cluster(requests):
    data = get_form(requests)
    job = jobAPI()
    m = job.get_searchmap_cluster(data)
    datas = {'mountain_map':m, 'data':data}
    return render(requests, 'jobMap/job_map_search.html', context=datas)

def job_map_search_heat(requests):
    data = get_form(requests)
    job = jobAPI()
    m = job.get_searchmap_heat(data)
    datas = {'mountain_map':m, 'data':data}
    return render(requests, 'jobMap/job_map_search.html', context=datas)

def paging(request, datalist, num=10):
    page = request.GET.get('page', '1')
    paginator = Paginator(datalist, num)
    page_obj = paginator.get_page(page)
    page = int(page)
    maxpage = num*((page-1)//num)+10
    minpage = num*((page-1)//num)+1
    return page_obj, maxpage, minpage

def job_map_search_list(requests):
    data = get_form(requests)
    job = jobAPI()
    if data['flag']==True:
        job.scrapping_jobkorea_search(data)
        if job.db.keyword.count()!=0:
            job.db.keyword.drop()
        job.db.keyword.insert_one(data)

    with MongoClient('mongodb://192.168.0.134:8088')  as client:
        Jobdata = client.Jobinfo
        contact_list = list(Jobdata.Joblist2.find())			# get Collection with find()

    page_obj, maxpage, minpage = paging(requests, contact_list)    
    data['page_obj'] = page_obj
    data['maxpage'] = maxpage
    data['minpage'] = minpage

    return render(requests, 'jobMap/job_map_search_list.html', context=data)

def job_map_all(requests):
    data = get_form(requests)
    job = jobAPI()
    m = job.get_allmap_heat(data)
    datas = {'mountain_map':m, 'data':data}
    return render(requests, 'jobMap/job_map_all.html', context=datas)

def listwithmongowithpaginator(request):
    data = request.GET.copy()
    with MongoClient('mongodb://192.168.0.134:8088')  as client:
        Jobdata = client.Jobdata
        contact_list = list(Jobdata.Joblist2.find())			# get Collection with find()
        data['page_obj'] = contact_list
        for info in contact_list:
            print(info)
    paginator = Paginator(contact_list, 10) # Show 15 contacts per page.

    page_number = request.GET.get('page', 1)
    # page_number = page_number if page_number else 1 
    data['page_obj'] = paginator.get_page(page_number)

    for _ in data['page_obj']:
        print("{row['company']}, {row['title']}, {row['address']}")

    return render(request, 'jobMap/listwithmongowithpaginator.html', context=data)

vivaMountainMap/views.py
from django.shortcuts import render
from pymongo import MongoClient
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from vivaMountainMap.mountainAPI import mountainAPI
from django.core.paginator import Paginator
import folium

url ='https://naveropenapi.apigw.ntruss.com/map-static/v2/raster'
headers={"X-NCP-APIGW-API-KEY-ID":"pyqaswux4u","X-NCP-APIGW-API-KEY":"BHD3BVoKqXuDP5TFujb0zxJIfeAU5YXy5fpCeSXk"}

# Create your views here.

def paging(request, datalist, num=10):
    page = request.GET.get('page', '1')
    paginator = Paginator(datalist, num)
    page_obj = paginator.get_page(page)
    page = int(page)
    maxpage = num*((page-1)//num)+10
    minpage = num*((page-1)//num)+1
    return page_obj, maxpage, minpage

def mountain_map(requests):
    mt = mountainAPI()
    m = mt.get_map()
    with MongoClient("mongodb://192.168.0.134:8088") as client:
        db = client.Mountain
        mountain_info = list(db.mountain_info.find())
        mountainList = list(db.mountainList.find())
        for i in range(len(mountain_info)):
            mountainList[i]['img'] =  mountain_info[i]['img']
    page_obj, maxpage, minpage = paging(requests, mountainList)  
    datas = {'mountain_map':m, 'page_obj':page_obj, 'maxpage':maxpage, 'minpage':minpage}
    return render(requests, 'vivaMountainMap/mountain_map.html', context=datas)

@csrf_exempt
def view_info(request,no):
    # if request.method == 'GET' :
    #     name = request.GET.get()

    with MongoClient("mongodb://192.168.0.134:8088") as my_client:
        data = dict()
        mountain = list(my_client.Mountain.mountain_info.find({'no':no}))
        mountaininfo = list(my_client.Mountain.placelist.find({'no':no}))
        mt = mountainAPI()
        m = mt.get_one_map(no)
        data = {'mountain':mountain, 'mountain_map':m, 'mountaininfo':mountaininfo}
        if data['mountain'] == None:
            return HttpResponse("<h1> 해당되는 산의 이름이 없습니다 </h1>")
        return render(request,'vivaMountainMap/moun_info.html',context=data)
        

templates/base.html
<!DOCTYPE html>
<html lang="en">
<title>위오동맹</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-bar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}
</style>
<body>

<!-- <div class="jumbotron text-center" style="margin-bottom:0">
    <h1>Hello Web</h1>
</div> -->

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href="{% url 'home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mountain:mountain_map' %}">Mountain</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'job:job_map_search' %}">Recruiting</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'job:job_map_all' %}">Experimental project</a>
            </li>
        </ul>
    </div>  
</nav>

{% block content %}
{% endblock %}

<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity">  
    <div class="w3-xlarge w3-padding-32">
      <i class="fa fa-facebook-official w3-hover-opacity"></i>
      <i class="fa fa-instagram w3-hover-opacity"></i>
      <i class="fa fa-snapchat w3-hover-opacity"></i>
      <i class="fa fa-pinterest-p w3-hover-opacity"></i>
      <i class="fa fa-twitter w3-hover-opacity"></i>
      <i class="fa fa-linkedin w3-hover-opacity"></i>
   </div>
   <p>Thank you for visiting</p>
   <p>위오동맹</p>
</footer>

<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
    } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>
</body>
</html>

templates/home/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- Header -->
<header class="w3-container w3-light-gray w3-center" style="padding:128px 16px; background: url('https://image.freepik.com/free-vector/sunset-mountains-landscape-with-gradient-colors_23-2148266711.jpg') no-repeat center center; background-size :cover;">
   <div class="container"> 
        <div class="row">
            <div class="col-lg-12 w3-animate-zoom"> 
                    <h1 class="w3-margin w3-jumbo"> Project </h1>
                    <h2 class="w3-margin w3-jumbo"> Smart Recruiting Map </h2>
                    <p class="w3-large">위 오 동 맹</p>
            </div>
        </div>
    </div> 
</header>

<!-- First Grid -->
<div class="w3-row-padding w3-padding-64 w3-container">
    <div class="w3-content">
        <div class="w3-twothird">
            <ul class="w3-ul">
                <li> <h1>Page discription</h1></li>
                    <li class="w3-hover-red">
                        <a href="/mountain/mountain_map/" style="color: black; text-decoration: none;">
                            <h4 >1. Mountain Map</h4>
                            <br>
                            <p style="margin-left: 1cm;">Blackyak와 산림청이 지정한 100대 명산지도를 아이콘과 함께 볼수 있습니다. <br>
                              아이콘 클릭시 팝업창으로 부터 오늘의 날씨와 위치정보를 볼 수 있고, 상세정보 링크를 통해 설명과 사진을 볼 수 있습니다.
                            </p>
                            
                        </a>
                    </li>
                    <li class="w3-hover-red">
                        <a href="/job/job_map_search/" style="color: black; text-decoration: none;">
                            <h4>2. Recruiting Map</h4>
                            <br>
                            <p style="margin-left: 1cm;">구직 정보를 맵에 표기한 페이지입니다. <br>
                              구직정보가 hitmap 또는 Clusturing 하여 표기 할 수 있습니다. <br>
                              검색을 통해 원하는 곳에 구할 수 있는 직장이 있는지에 대한 여부를 확인하세요!
                            
                            </p>
              
                        </a>
                    </li>
            </ul>
        </div>
    </div>
</div>

<div class="container">
  <div class="w3-content">
    <div class="w3-twothird">
      <ul>
          <li><h2> Team Info</h2></li>
          <br>
          <div class="media border p-3">
              <img src="{% static '/img/img_avatar3.png' %}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
              <div class="media-body">
                <h4>조 준 희 </h4><span style="color: orangered;"> 조 장 </span>
                <ul>
                <li>html 페이지 작성 및 데이터 정리</li>            
                <li>각종 기능 함수 구현</li>  
                <li> folium 맵 작성 및 정보 표기</li>
              </ul>
                
              </div>
            </div>
            <div class="media border p-3">
              <img src="{% static '/img/img_avatar3.png' %}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
              <div class="media-body">
                <h4>조 국 현 </h4>
                <span style="color: orangered;">팀원 1 </span>
                <ul>
                  <li>데이터 스크랩핑</li>            
                  <li>각종 기능 함수 구현</li>  
                </ul>    
                
              </div>
            </div>
            <div class="media border p-3">
              <img id='img1' src="{% static '/img/img_avatar3.png' %}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
              <div class="media-body">
                <h4>손 상 훈 </h4>
                <span style="color: orangered;">팀원 1 </span>
                <ul>
                  <li>html 페이지 꾸밈 작업</li>            
                  <li>html 페이징 작업</li>  
                </ul>
                
              </div>
            </div>
      </ul>
    </div>
  </div>
</div>

{% endblock %}

templates/jobMap/job_map.html
{% extends 'base.html' %}
{% block content %}

    <div class="container p-3 my-3 border">
            <h1>Job map in Jobkorea</h1><br>
            <h5>We show ---/h5>
    </div>
    <div class="container">
        <div class="row">
            <!-- <div class="col-8"> -->
            <div class="col">
                {{mountain_map|safe}}
            </div>
        </div>
    </div>




{% endblock %}

templates/jobMap/job_map_all.html
{% extends 'base.html' %}
{% block content %}

    <div class="container p-3 my-3 border">
            <h1>Job map about total recruiting information in Worknet</h1><br>
            <h5>Experimantal project</h5>
            <p></p>
            <div class="btn-group">
                <a href="{% url 'job:job_map_all' %}" class="btn btn-outline-danger" role="button">Heat Map</a>
            </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                {{mountain_map|safe}}
            </div>
        </div>
    </div>

{% endblock %}

templates/jobMap/job_map_search.html
{% extends 'base.html' %}
{% block content %}

    <div class="container p-3 my-3 border">
            <h1>Job map in Jobkorea</h1><br>
            <h5>We show Recruiting Map for jobseeker</h5>
            <form action="", method="get">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>    
                            <th>Career Type: 
                                {% if data.careerType == '1' %}
                                    신입
                                {% elif data.careerType == '2' %}
                                    경력
                                {% elif data.careerType == '3' %}
                                    신입+경력
                                {% elif data.careerType == '4' %}
                                    경력무관
                                {% else %}
                                    전체
                                {% endif %}
                            </th>
                            <th>Current Keyword: {{data.keyword}}</th>
                            <th>Max Page: {{data.max_page}}</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <div class="input-group mb-3">
                            <td>
                                <!-- <label for="sel1">Select list:</label> -->
                                <select class="form-control" id="sel1", name="careerType">
                                    <option value="">전체</option>
                                    <option value="1">신입</option>
                                    <option value="2">경력</option>
                                    <option value="3">신입+경력</option>
                                    <option value="4">경력무관</option>
                                </div>
                            </td>
                            <td><input type="text" class="form-control" placeholder="job keyword", name="key"></td>
                            <td><input type="text" class="form-control" placeholder="max page", name="max_page"></td>
                            <td>
                                <input type="submit" class="btn btn-dark", value="Submit">
                                <a href="{% url 'job:job_map_search_list' %}" class="btn btn-danger" style="margin-left: 1%;" role="button">List</a>
                            </td>
                            </div>
                        </tr>
                    </tbody>
                </table>
            </form>
            <p></p>
            <div class="btn-group">
                <a href="{% url 'job:job_map_search' %}" class="btn btn-outline-primary" role="button">Basic Map</a>
                <a href="{% url 'job:job_map_search_cluster' %}" class="btn btn-outline-info" role="button">Clustering Map</a>
                <a href="{% url 'job:job_map_search_heat' %}" class="btn btn-outline-danger" role="button">Heat Map</a>
            </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                {{mountain_map|safe}}
            </div>
        </div>
    </div>

{% endblock %}

templates/jobMap/job_map_search_list.html
{% extends 'base.html' %}
{% block content %}

    <div class="container p-3 my-3 border">
            <h1>Job map in Jobkorea</h1><br>
            <h5>We show Recruiting Map for jobseeker</h5>
            <form action="", method="get">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>    
                            <th>Career Type: 
                                {% if data.careerType == '1' %}
                                    신입
                                {% elif data.careerType == '2' %}
                                    경력
                                {% elif data.careerType == '3' %}
                                    신입+경력
                                {% elif data.careerType == '4' %}
                                    경력무관
                                {% else %}
                                    전체
                                {% endif %}
                            </th>
                            <th>Current Keyword: {{data.keyword}}</th>
                            <th>Max Page: {{data.max_page}}</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <div class="input-group mb-3">
                            <td>
                                <!-- <label for="sel1">Select list:</label> -->
                                <select class="form-control" id="sel1", name="careerType">
                                    <option value="">전체</option>
                                    <option value="1">신입</option>
                                    <option value="2">경력</option>
                                    <option value="3">신입+경력</option>
                                    <option value="4">경력무관</option>
                                </div>
                            </td>
                            <td><input type="text" class="form-control" placeholder="job keyword", name="key"></td>
                            <td><input type="text" class="form-control" placeholder="max page", name="max_page"></td>
                            <td>
                                <input type="submit" class="btn btn-dark", value="Submit">
                                <a href="{% url 'job:job_map_search_list' %}" class="btn btn-danger" style="margin-left: 1%;" role="button">List</a>
                            </td>
                            </div>
                        </tr>
                    </tbody>
                </table>
            </form>
            <p></p>
            <div class="btn-group">
                <a href="{% url 'job:job_map_search' %}" class="btn btn-outline-primary" role="button">Basic Map</a>
                <a href="{% url 'job:job_map_search_cluster' %}" class="btn btn-outline-info" role="button">Clustering Map</a>
                <a href="{% url 'job:job_map_search_heat' %}" class="btn btn-outline-danger" role="button">Heat Map</a>
            </div>
    </div>
    <div class="container">
        <div class="row">
            <!-- <div class="col-8"> -->
            <div class="col">
                <div class="container">
                    <table class="table table-striped table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th>company</th>
                                <th>title</th>
                                <th>address</th>
                            </tr>
                        </thead>
                        <tbody id="example-table-1">
                            {% for row in page_obj %}
                            <tr name="link" value="{{row.link}}">
                                <td>{{row.company}}</td>
                                <td>{{row.title}}</td>
                                <td>{{row.address}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                
                    {% include 'paginator.html' %}
                </div>
            </div>
        </div>
    </div>

<script>
// 테이블의 행을 눌러서 실행
$("#example-table-1 tr").click(function(){ 	
    var str = ""
    var tdArr = new Array();	// 배열 선언
    var tr = $(this);
    var td = tr.children();
    td.each(function(i){
        tdArr.push(td.eq(i).text());
    });
    console.log(tr[0].getAttribute('value'))
    location.href=tr[0].getAttribute('value');
});
</script>
{% endblock %}

templates/jobMap/listwithmongowithpaginator.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>company</th>
                <th>title</th>
                <th>address</th>
            </tr>
        </thead>
        <tbody>
            {% for row in page_obj.0 %}
            <tr>
                <td><a href={{row.link}} style="color:black">{{row.company}}</a></td>
                <td>{{row.title}}</td>
                <td>{{row.address}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

<!-- 페이지네이터 임시 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if page_obj.0.has_previous  %}
    <li class="page-item">
        <a class="page-link" href="?page=1">First</a>
    </li>
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.0.previous_page_number }}">Prev</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">First</a>
    </li>
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Prev</a>
    </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in page_obj.0.paginator.page_range %}
        {% if page_number >= page_obj.0.number|add:"-4" and page_number <=  page_obj.0.number|add:"4"  %}
            {% if page_number == page_obj.0.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if page_obj.0.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.0.next_page_number }}">Next</a>
    </li>
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.0.paginator.num_pages }}">Last</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
    </li>
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Last</a>
    </li>
    {% endif %}
</ul>
</div>

{% endblock %}

templates/paginator.html
<!-- 페이지네이터 임시 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if page_obj.has_previous  %}
    <li class="page-item">
        <a class="page-link text-dark" href="?page=1">First</a>
    </li>
    <li class="page-item">
        <a class="page-link text-dark" href="?page={{ page_obj.previous_page_number }}">Prev</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link text-dark" tabindex="-1" aria-disabled="true" href="#">First</a>
    </li>
    <li class="page-item disabled">
        <a class="page-link text-dark" tabindex="-1" aria-disabled="true" href="#">Prev</a>
    </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in page_obj.paginator.page_range %}
        {% if page_number >= minpage and page_number <=  maxpage  %}
            {% if page_number == page_obj.number %}
            <li class="page-item" aria-current="page">
                <a class="page-link text-white bg-dark " href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link text-dark" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link text-dark" href="?page={{ page_obj.next_page_number }}">Next</a>
    </li>
    <li class="page-item">
        <a class="page-link text-dark" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link text-dark" tabindex="-1" aria-disabled="true" href="#">Next</a>
    </li>
    <li class="page-item disabled">
        <a class="page-link text-dark" tabindex="-1" aria-disabled="true" href="#">Last</a>
    </li>
    {% endif %}
</ul>

templates/vivaMountainMap/moun_info.html
{% extends 'base.html' %}
{% block content %}

<div class='container jumbotron border'>
    <table>
        <colgroup>
            <col width="40%">
            <col width="5%">
            <col width="*%">
        </colgroup>
        <tr>
            <td>
                <div>
                    <img class="img-fluid" src={{mountain.0.img}}>
                </div>
            </td>
            <td></td>
            <td>
                <div class=''> 
                    <div class="container">
                    <h2>
                        {{mountain.0.name}}
                    </h2>
                    <p>
                        {% if mountain.0.info == None %}        
                        {% else %}
                            <li>{{mountain.0.info}}</li>
                        {% endif %}
                    </p>
                    <li>GPS 좌표 : {{mountain.0.x}} <span> | </span> {{mountain.0.y}}</li>
                    <li>주소 : {{mountaininfo.0.address_name}}</li>
                </div>
                </div>           
            </td>            
        </tr>
    </table>
    <div class="container"><a href="{% url 'mountain:mountain_map' %}" class='btn btn-dark float-right' role="button">목록</a></div>
    
</div>
<div class="container">
    <div class="row">
        <!-- <div class="col-8"> -->
        <div class="col">
            <div class="container">
                {{mountain_map|safe}}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/vivaMountainMap/moun_map.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col"><h1>map result comes here</h1></div>
        <div class="col">{{mountain_map|safe}}</div>
    </div>
</div>

{% endblock %}

templates/vivaMountainMap/mountain_map.html
{% extends 'base.html' %}
{% block content %}

<div class="container p-3 my-3 border">
        <h1>Mountain map in Korea</h1><br>
        <h5>We show famous mountains in Korea</h5>
</div>
<div class="container" style="margin-bottom: 1cm;">
    <div class="row">
        <!-- <div class="col-8"> -->
        <div class="col">
            {{mountain_map|safe}}
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col ">
            <div class="container">
                <table class="table table-striped table-hover">
                    <colgroup>
                        <col width="25%"/>
                        <col width="25">
                        <col width="25%"/>
                        <col width="25%"/>
                    </colgroup>
                    <thead class="thead-dark">
                        <tr>
                            <th>산이름</th>
                            <th>지역</th>
                            <th>높이</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="example-table-1">
                        {% for row in page_obj %}
                        <tr name="link" value="{{row.no}}">
                            <td class="align-middle">{{row.name}}</td>
                            <td class="align-middle">{{row.area}}</td>
                            <td class="align-middle">{{row.height}}</td>
                            <td class="align-middle"><img src="{{row.img}}" alt="{{row.name}}"  height="128"></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% include "paginator.html" %}
        </div>
    </div>
</div>
<script>
    // 테이블의 행을 눌러서 실행
    $("#example-table-1 tr").click(function(){ 	
        var str = ""
        var tdArr = new Array();	// 배열 선언
        var tr = $(this);
        var td = tr.children();
        td.each(function(i){
            tdArr.push(td.eq(i).text());
        });
        location.href="/mountain/mountain_map/info/" + tr[0].getAttribute('value');
    });
</script>
{% endblock %}